// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteData(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteData'](arg1, arg2, arg3);
}

export function GetDataByDate(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDataByDate'](arg1, arg2, arg3);
}

export function GetDataList(arg1, arg2) {
  return window['go']['main']['App']['GetDataList'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function List(arg1) {
  return window['go']['main']['App']['List'](arg1);
}

export function SaveData(arg1) {
  return window['go']['main']['App']['SaveData'](arg1);
}

export function UpdateData(arg1) {
  return window['go']['main']['App']['UpdateData'](arg1);
}
