// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteData(arg1:string,arg2:string,arg3:string):Promise<main.H>;

export function GetDataByDate(arg1:Array<string>,arg2:number,arg3:number):Promise<main.H>;

export function GetDataList(arg1:number,arg2:number):Promise<main.H>;

export function Greet(arg1:string):Promise<string>;

export function List(arg1:string):Promise<any>;

export function SaveData(arg1:any):Promise<main.H>;

export function UpdateData(arg1:any):Promise<main.H>;
